site_name: Reputation Monitor
docs_dir: docs
site_dir: site

# Repository
repo_name: pranav271103/Reputation-Monitor
repo_url: https://github.com/pranav271103/Reputation-Monitor

# Theme
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.sections
    - navigation.top
    - navigation.footer
    - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

# Copyright
copyright: "Copyright &copy; 2023 Reputation Monitor"

# Development server
dev_addr: '127.0.0.1:8000'

# Build options
use_directory_urls: true

# Edit URI
edit_uri: edit/main/docs/

# Markdown extensions
markdown_extensions:
  - toc:
      permalink: true
  - tables
  - fenced_code
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.tilde

# Strict mode (enables extra validation)
strict: false  # Temporarily disabled to allow build to complete

# Navigation
nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - User Guide: user_guide.md
  - API Reference: api_reference.md
  - Developer Guide: developer_guide.md
  - Troubleshooting: troubleshooting.md

# Extra configuration
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/pranav271103/Reputation-Monitor

# GitHub integration
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/pranav271103/Online-bad-reputation-
